CREATE TABLE IF NOT EXISTS public."user" (
    user_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    password_hash text NOT NULL,
    email text UNIQUE,
    favorite_genre text
);

CREATE TABLE IF NOT EXISTS public.media (
    media_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_user_id integer NOT NULL REFERENCES public."user"(user_id),
    title text NOT NULL,
    description text,
    media_type text NOT NULL,
    release_year integer,
    genres text,
    age_restriction integer,
    average_rating real DEFAULT 0
    );

CREATE TABLE IF NOT EXISTS public.rating (
    rating_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id integer NOT NULL REFERENCES public.media(media_id),
    user_id integer NOT NULL REFERENCES public."user"(user_id),
    stars integer NOT NULL CHECK (stars >= 1 AND stars <= 5),
    comment text,
    confirmed boolean NOT NULL DEFAULT false,
    likes integer NOT NULL DEFAULT 0,
    timestamp text
    );

CREATE TABLE IF NOT EXISTS public.favorite (
    user_id integer NOT NULL REFERENCES public."user"(user_id),
    media_id integer NOT NULL REFERENCES public.media(media_id),
    PRIMARY KEY (user_id, media_id)
    );